In [2]:
my_list = [1,2,3,4,5]

In [5]:
import numpy as np

In [6]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3, 4, 5])

conclusion: so we can cast python list to numpy array


In [9]:
my_mat = [[1,2,3],[11,22,33],[111,222,333]]

In [10]:
np.array(my_mat)

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

to generate array we can use (np.arange([start,]stop[, stop,],dtype=none)) but remember that stop execulde from array

In [11]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

to generate array of zeros we use (np.zeros(digits))


In [13]:
np.zeros(3)

array([0., 0., 0.])

or we can pass the matrix length to zeros as tuple


In [15]:
np.zeros((3,3))#(rows,columns)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((2,3))#just like zeros  but it generate array of ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones((4))

array([1., 1., 1., 1.])

In [30]:
np.linspace(1,2,7)

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        ])

In [31]:
np.eye(4)#id matrix that mean digonal is one and all zeros  and must be squar

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.random.rand(5)*9#random number from zero to one using unformal distrubution

array([5.12092914, 4.40930042, 5.99152532, 8.47656014, 4.58853443])

In [48]:
np.random.rand(2,3)*9

array([[3.20627276, 5.51989017, 0.43129227],
       [8.19192275, 7.76050829, 7.97574763]])

In [50]:
np.random.randn(3)*9#return sample of 2 not from normal distrubtion but from stander normal dist around zero

array([-8.91540863,  0.63746542, 10.0380587 ])

In [51]:
np.random.randn(2,2)

array([[ 0.33702369,  1.26116513],
       [-0.55191544, -1.18005369]])

In [58]:
np.random.randint(1,30)#return random number between (1,30) and  you can pass third argument to retunr spacific number  

22

In [59]:
np.random.randint(1,300,5)

array([ 74, 225, 215, 135,  57])

In [68]:
arr = np.arange(40)

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [83]:
randarr = np.random.randint(1,100,10)

In [84]:
randarr

array([27, 33, 16, 60, 89, 17, 86, 44, 90, 74])

In [72]:
arr.reshape(4,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [85]:
randarr.max()#to get max number in array

90

In [86]:
randarr.min()#return the min numer in array

16

In [87]:
randarr.argmax()#return the index of max number in array 

8

In [88]:
randarr.argmin()#return the index of min number in array

2

In [92]:
arr.shape#to get shape of array and shape is attribute s call it without ()

(40,)

In [93]:
arr.dtype#to get the data type of array but remember that call it without -> ()

dtype('int64')

In [96]:
np.random.randint(3,10,100)

array([7, 7, 8, 7, 4, 3, 3, 7, 4, 9, 3, 3, 4, 5, 9, 5, 9, 7, 3, 5, 7, 7,
       6, 7, 8, 9, 3, 3, 9, 8, 6, 5, 6, 3, 6, 7, 3, 3, 8, 9, 6, 5, 3, 6,
       8, 8, 8, 3, 4, 6, 5, 9, 9, 5, 8, 6, 8, 9, 8, 5, 8, 8, 9, 8, 9, 8,
       3, 8, 9, 9, 6, 7, 7, 6, 3, 8, 9, 9, 7, 8, 5, 3, 9, 7, 4, 4, 9, 8,
       3, 6, 5, 7, 9, 5, 3, 6, 7, 8, 6, 6])