In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[4]

4

In [7]:
arr[1:5]#execlude the last element

array([1, 2, 3, 4])

In [8]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr[0:11]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr[0:2]=100#to update a collection of indexinf at the same time

In [15]:
arr= np.arange(0,11)

In [16]:
slice_of_array = arr[0:5]

In [18]:
slice_of_array[0:]=100

In [20]:
slice_of_array

array([100, 100, 100, 100, 100])

In [21]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

to avoid this issue we can do copy of array using (arr.copy())
numpy using this technique to avoid memory leak

In [22]:
slice_of_array=arr[0:5].copy()

In [24]:
slice_of_array[0:]=1000

In [25]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

#-----------------------------------------------------

In [26]:
arr_2d=np.array([[1,2,3],[11,22,33],[111,222,333]])

In [27]:
arr_2d

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [28]:
arr_2d[1][1]

22

In [29]:
arr_2d[1,1]#recomanded to use it

22

In [30]:
arr_2d[:2,1:]#

array([[ 2,  3],
       [22, 33]])

In [31]:
arr_2d[:2]

array([[ 1,  2,  3],
       [11, 22, 33]])

In [32]:
arr_2d[1:,:]

array([[ 11,  22,  33],
       [111, 222, 333]])

In [37]:
bool_arr = arr_2d > 10 #this will return bool array

In [38]:
bool_arr

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [36]:
arr_2d[bool_arr]#this will return the true value

array([ 11,  22,  33, 111, 222, 333])

In [39]:
arr_2d[arr_2d>10]

array([ 11,  22,  33, 111, 222, 333])

exercies

In [40]:
exer_arr = np.arange(60).reshape(6,10)

In [41]:
exer_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [42]:
exer_arr[3:,1:]

array([[31, 32, 33, 34, 35, 36, 37, 38, 39],
       [41, 42, 43, 44, 45, 46, 47, 48, 49],
       [51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [44]:
exer_arr[1:3,3:5]

array([[13, 14],
       [23, 24]])